cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log
  plugins: /elasticsearch/plugins
  work: /data/work

bootstrap.mlockall: true

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}

cloud:
  aws:
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}
discovery:
    type: ec2
    zen.ping.multicast.enabled: false
    zen.minimum_master_nodes: ${MINIMUM_MASTERS}
    ec2:
      groups:
        - ${ES_DISCOVERY_SG}
      ping_timeout: '3s'
